version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: laravel-nginx # 容器名
    restart: always
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d #把容器的conf.d映射到 ./nginx/conf.d
      - ./:/usr/share/html
    ports:
      - "8080:80"
      - "8081:81"